# Site settings
title: DISC Test
email:
author:
description:
url:

# Build settings
page_gen:
  - data: 'questions'
    template: 'question'
    name: 'position'
    dir: 'questions/profile'
    filter_condition: "record['type'] == 'profile'"

sass:
  sass_dir: css
